### ISSUE TITLE
crypto_box_seal(challenge, publicKey);

### ISSUE THREAD

**Issue by c128128** [devtomio/sodium#14]
Not sure, maybe I am doing something wrong.

Calling `crypto_box_seal(challenge, publicKey);`

Getting:
```thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("ciphertext length invalid (0 != 80, from dryoc/src/classic/crypto_box.rs:220")', src/crypto_box.rs:198:10```

**Comment by devtomio** [comment]
I will be looking into this.

**Comment by devtomio** [comment]
I have implemented a fix let's just wait for the [`ci`](https://github.com/devtomio/sodium/actions/runs/2040398564) to finish.

**Comment by devtomio** [comment]
Can you try version [`0.2.0`](https://www.npmjs.com/package/@devtomio/sodium/v/0.2.0)?

cc: @c128128

**Comment by devtomio** [comment]
Closing this as I tested this and it is fixed.
